### ISSUE TITLE
Build legacy kern table by default?

### ISSUE THREAD

**Issue by madig** [daltonmaag/ubuntu#16]
Why is building the legacy kern table a separate step that will not trigger by default?

**Comment by anthrotype** [comment]
I don't remember. @moyogo?

**Comment by moyogo** [comment]
Hmm, not sure. It can be done by default.

**Comment by madig** [comment]
Okay, then the binaries to be distributed would be in build/legacy_kern? And why don't the Mono fonts get legacy kerning?

**Comment by anthrotype** [comment]
Mono spaced fonts don’t need kerning

**Comment by madig** [comment]
Doh. Right. 😬

**Comment by madig** [comment]
Solved by https://github.com/daltonmaag/ubuntu/pull/20, the legacy kern table is now applied to the final TTFs in `build/`.
