### ISSUE TITLE
Migrate build system from 'fontmake' to 'ufo2ft'

### ISSUE THREAD

**Issue by sladen** [daltonmaag/ubuntu#19]
_Per @anthrotype in daltonmaag/ubuntu/pull/14#issuecomment-348476334_:

The build system can probably be simplified to use just `ufo2ft`—close to what daltonmaag/scope-one uses.  Possible minimal implementation suggested by @anthrotype:

```python
import sys
import logging
import defcon
import ufo2ft
import vttLib


def main(args=None):
    if args is None:
        args = sys.argv[1:]

    if len(args) < 2:
        print("usage: build.py INPUT.ufo OUTPUT.ttf")
        return 2

    logging.basicConfig(level="INFO")

    ufo_path = args[0]
    ttf_path = args[1]

    ufo = defcon.Font(ufo_path)

    ttf = ufo2ft.compileTTF(ufo,
                            useProductionNames=False,
                            convertCubics=False)

    ttf.save(ttf_path)

    # merge VTT TSI* tables and maxp data
    vttLib.vtt_merge(ufo_path, ttf_path)

if __name__ == "__main__":
    sys.exit(main())
```
_See also daltonmaag/scope-one/blob/master/build.sh_

**Comment by madig** [comment]
This is clever, but very specific to Ubuntu's current circumstances. Advances in archaeology and reverse engineering might make it necessary to change this again, though that's okay I guess.

**Comment by sladen** [comment]
Yup, the minimal implementation probably doesn't make sense.  But, sharing common tooling across multiple fonts _does_ make sense.

_(The hopeful end goal being to have universal tooling that one can run a whole company on!)._

**Comment by madig** [comment]
Well, that common tooling would probably involve fontmake in some capacity... Though this is a fun diversion. Might look at adding in the legacy kerning while I'm at it.

**Comment by anthrotype** [comment]
it shouldn't be long before we add that --output-file option to fontmake. But the four-line build.py is totally legit (and less hacky than the other find-fontmake-name.py). You're calling the same public API that fontmake is. Also I follow semver for versioning ufo2ft and the rest, and rarely break interface, usually deprecate stuff in advance, etc. it's ok

**Comment by madig** [comment]
Hm. So merging kern_table.py into build.py is also temporary :)

Would be nice to be able to hook custom pre/post-processing code into fontmake for projects like this.

**Comment by anthrotype** [comment]
it could be done, yes. Something like extending the ufo2ft postProcessor.
If a special key is present in a UFO's lib, then ufo2ft would attempt to import a class from a user-specified module providing this functionality.
We need to discuss and think this though better.
You could open an issue over at ufo2ft repo so we gather thoughts

**Comment by sladen** [comment]
It's entirely possible that the conclusion of this issue, is that using `uto2ft` directly doesn't make sense.  The ideal outcome is to use standardised tooling that benefits everyone including Dalton Maag, and to improve/tweak/patch those tools upstream if they don't currently have the capability required.

One of the other potential downside of `fontmake` compared to the above appears to be serialisation out to files on disk, then re-reading/re-parsing back in.  Verses a single script that would keep everything in-memory, just passing objects around.

**Comment by anthrotype** [comment]
I don't believe a single console script like fontmake (because that's what is, just a the fronted to to ufo2ft, the library that actually compiles) could ever be able to cater for all the needs of each specific projects. And ubuntu can hardly be qualified as "standard" project, with its history and its special requirements.
having said that, we spent more time discussing how to proceed than we could have spent actually fixing fontmake... :stuck_out_tongue_closed_eyes:

**Comment by moyogo** [comment]
@anthrotype FWIW, fontmake should handle building legacy kerntable, for the sake of compatibility with GlyphsApp and its `Write Kern Table` customParameter.
However this doesn’t guarantee that the kern table will be built as we want for Ubuntu, so we’d still need a more flexible way to do so.

**Comment by anthrotype** [comment]
I'd love to make each step of the ufo2ft compilation customizable via plug-ins, similar to the way pytest or tox do (they make use of https://github.com/pytest-dev/pluggy). But this will take time...

**Comment by madig** [comment]
The discussion helps narrowing down the problem :)

Keep in mind that Ubuntu might not be the only font family that has a "special" history. Just think of all the fonts that were not made with today's tooling. See https://github.com/google/fonts/issues/6, Adam Twardoch describes how he's the only one who can build Lato and that's a show stopper.

**Comment by anthrotype** [comment]
> Ubuntu might not be the only font family that has a "special" history

that was exactly my point. every project is special in its own and is perfectly fine to have ad-hoc scripts to accomplish the building, provided these scripts also use "standard" open source libraries

**Comment by madig** [comment]
Done by #20. The build system can be revisited once fontmake or ufo2ft grow the necessary plugin capabilities.

**Comment by sladen** [comment]
Close per @madig in comment above.
Feel free to re-open if required.
