### ISSUE TITLE
No sources for release 0.862

### ISSUE THREAD

**Issue by fitojb** [daltonmaag/ubuntu#74]
cc @seb128

**Comment by seb128** [comment]
?

**Comment by fitojb** [comment]
There is no source code for the just-announced binary release of the font family. Or, at least, there is no new public branch in this repository

**Comment by seb128** [comment]
you didn't provide much context did you, I'm not familiar with the repository here and you didn't even mention the word font. I guess you want https://github.com/canonical/Ubuntu-fonts/ ?

**Comment by fitojb** [comment]
... which was not public until very recently, and I follow the Canonical GitHub organization. This was the repository mentioned as the upstream project mentioned in the official Ubuntu Wiki. Please don’t blame community members for not being able to follow if not even Canonical employees know about the heritage of one of their own projects.

**Comment by seb128** [comment]
I was not blaming, but you can understand that tagging someone on a random project without specifying the context can be confusing right? you didn't even mention it was about the font and I've no idea what daltonmaag is, I'm not directly involved in the font work just got asked to push an update for Ubuntu
