### ISSUE TITLE
Store maxp table in data folder instead of lib.plist.

### ISSUE THREAD

**Issue by madig** [daltonmaag/ubuntu#8]
vttLib 0.7.4 warns: `WARNING: storing maxp in lib.plist is deprecated; use data folder instead`

**Comment by anthrotype** [comment]
you need to re-run `python -m vttLib dump font.ttf [font.ufo]` to export the maxp data to the UFO data subfolder

**Comment by madig** [comment]
Fixed by PR https://github.com/daltonmaag/ubuntu/pull/15.
