### ISSUE TITLE
The build process leaves binaries in the source directory

### ISSUE THREAD

**Issue by madig** [daltonmaag/ubuntu#9]
Everything should be placed into `build/`.

**Comment by anthrotype** [comment]
it is intentional.
those binary TTFs in the source directory are really (temporary) source files for VTT, potentially to be manually edited.

the actual final artifacts are to be found in the `build` folder, with the hinting source data compiled using vttLib and fonttools.

**Comment by anthrotype** [comment]
and all *.ttf are .gitignored

**Comment by madig** [comment]
Mh. The janitor inside me wants to move everything over to the build dir, as the VTT stuff should be edited inside the UFOs.

**Comment by anthrotype** [comment]
> the VTT stuff should be edited inside the UFOs.

that's impossible! you need a TTF to open it up inside VTT, the proprietary GUI editor.

**Comment by madig** [comment]
Ah, okay. That's horrible. But I can close the bug then.

**Comment by sladen** [comment]
This can be reopened later if a better solution comes (ie. place them in another directory) comes to light.  Debian packaging likes to be able to reliably clean-up.
